package com.zsq.module;

import com.comm.util.BaseForm;

public class CmsTopic extends BaseForm {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.id
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private Long id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.customer_id
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private Long customerId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.topic_id
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private Long topicId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.topic_name
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private String topicName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.topic_type
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private Integer topicType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.topic_discuss
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private String topicDiscuss;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.topic_url
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private String topicUrl;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.tpl_path
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private String tplPath;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.page_storage_path
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private String pageStoragePath;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.web_storage_path
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private String webStoragePath;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.create_time
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private String createTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.publish_time
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private String publishTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.last_reply_time
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private String lastReplyTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.collection_num
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private Long collectionNum;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.review_num
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private Long reviewNum;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.reprint_num
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private Long reprintNum;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.share_num
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private Long shareNum;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.prefer_up_num
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private Long preferUpNum;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.browse_num
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private Long browseNum;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.follow_fans_num
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private Long followFansNum;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.is_customer_essential
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private Integer isCustomerEssential;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.is_sys_essential
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private Integer isSysEssential;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.is_header
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private Integer isHeader;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.sort_id
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private Integer sortId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column cms_topic.is_valid
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    private Integer isValid;
    
    private Integer sendSiteId;
    
    private Long sortListAuthority;
    
    private Long sortAuthoritySecondary;
    
    private Integer isDraft;
    private String sharePageShortUrl;
    private String shareWebShortUrl;
    private String appStoragePath;

    public String getSharePageShortUrl() {
		return sharePageShortUrl;
	}

	public void setSharePageShortUrl(String sharePageShortUrl) {
		this.sharePageShortUrl = sharePageShortUrl;
	}

	public String getShareWebShortUrl() {
		return shareWebShortUrl;
	}

	public void setShareWebShortUrl(String shareWebShortUrl) {
		this.shareWebShortUrl = shareWebShortUrl;
	}

	public String getAppStoragePath() {
		return appStoragePath;
	}

	public void setAppStoragePath(String appStoragePath) {
		this.appStoragePath = appStoragePath;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.id
     *
     * @return the value of cms_topic.id
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.id
     *
     * @param id the value for cms_topic.id
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.customer_id
     *
     * @return the value of cms_topic.customer_id
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.customer_id
     *
     * @param customerId the value for cms_topic.customer_id
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.topic_id
     *
     * @return the value of cms_topic.topic_id
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.topic_id
     *
     * @param topicId the value for cms_topic.topic_id
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.topic_name
     *
     * @return the value of cms_topic.topic_name
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public String getTopicName() {
        return topicName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.topic_name
     *
     * @param topicName the value for cms_topic.topic_name
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setTopicName(String topicName) {
        this.topicName = topicName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.topic_type
     *
     * @return the value of cms_topic.topic_type
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public Integer getTopicType() {
        return topicType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.topic_type
     *
     * @param topicType the value for cms_topic.topic_type
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setTopicType(Integer topicType) {
        this.topicType = topicType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.topic_discuss
     *
     * @return the value of cms_topic.topic_discuss
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public String getTopicDiscuss() {
        return topicDiscuss;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.topic_discuss
     *
     * @param topicDiscuss the value for cms_topic.topic_discuss
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setTopicDiscuss(String topicDiscuss) {
        this.topicDiscuss = topicDiscuss;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.topic_url
     *
     * @return the value of cms_topic.topic_url
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public String getTopicUrl() {
        return topicUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.topic_url
     *
     * @param topicUrl the value for cms_topic.topic_url
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setTopicUrl(String topicUrl) {
        this.topicUrl = topicUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.tpl_path
     *
     * @return the value of cms_topic.tpl_path
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public String getTplPath() {
        return tplPath;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.tpl_path
     *
     * @param tplPath the value for cms_topic.tpl_path
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setTplPath(String tplPath) {
        this.tplPath = tplPath;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.page_storage_path
     *
     * @return the value of cms_topic.page_storage_path
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public String getPageStoragePath() {
        return pageStoragePath;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.page_storage_path
     *
     * @param pageStoragePath the value for cms_topic.page_storage_path
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setPageStoragePath(String pageStoragePath) {
        this.pageStoragePath = pageStoragePath;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.web_storage_path
     *
     * @return the value of cms_topic.web_storage_path
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public String getWebStoragePath() {
        return webStoragePath;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.web_storage_path
     *
     * @param webStoragePath the value for cms_topic.web_storage_path
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setWebStoragePath(String webStoragePath) {
        this.webStoragePath = webStoragePath;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.create_time
     *
     * @return the value of cms_topic.create_time
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.create_time
     *
     * @param createTime the value for cms_topic.create_time
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.publish_time
     *
     * @return the value of cms_topic.publish_time
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public String getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.publish_time
     *
     * @param publishTime the value for cms_topic.publish_time
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setPublishTime(String publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.last_reply_time
     *
     * @return the value of cms_topic.last_reply_time
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public String getLastReplyTime() {
        return lastReplyTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.last_reply_time
     *
     * @param lastReplyTime the value for cms_topic.last_reply_time
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setLastReplyTime(String lastReplyTime) {
        this.lastReplyTime = lastReplyTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.collection_num
     *
     * @return the value of cms_topic.collection_num
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public Long getCollectionNum() {
        return collectionNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.collection_num
     *
     * @param collectionNum the value for cms_topic.collection_num
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setCollectionNum(Long collectionNum) {
        this.collectionNum = collectionNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.review_num
     *
     * @return the value of cms_topic.review_num
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public Long getReviewNum() {
        return reviewNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.review_num
     *
     * @param reviewNum the value for cms_topic.review_num
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setReviewNum(Long reviewNum) {
        this.reviewNum = reviewNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.reprint_num
     *
     * @return the value of cms_topic.reprint_num
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public Long getReprintNum() {
        return reprintNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.reprint_num
     *
     * @param reprintNum the value for cms_topic.reprint_num
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setReprintNum(Long reprintNum) {
        this.reprintNum = reprintNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.share_num
     *
     * @return the value of cms_topic.share_num
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public Long getShareNum() {
        return shareNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.share_num
     *
     * @param shareNum the value for cms_topic.share_num
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setShareNum(Long shareNum) {
        this.shareNum = shareNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.prefer_up_num
     *
     * @return the value of cms_topic.prefer_up_num
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public Long getPreferUpNum() {
        return preferUpNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.prefer_up_num
     *
     * @param preferUpNum the value for cms_topic.prefer_up_num
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setPreferUpNum(Long preferUpNum) {
        this.preferUpNum = preferUpNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.browse_num
     *
     * @return the value of cms_topic.browse_num
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public Long getBrowseNum() {
        return browseNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.browse_num
     *
     * @param browseNum the value for cms_topic.browse_num
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setBrowseNum(Long browseNum) {
        this.browseNum = browseNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.follow_fans_num
     *
     * @return the value of cms_topic.follow_fans_num
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public Long getFollowFansNum() {
        return followFansNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.follow_fans_num
     *
     * @param followFansNum the value for cms_topic.follow_fans_num
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setFollowFansNum(Long followFansNum) {
        this.followFansNum = followFansNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.is_customer_essential
     *
     * @return the value of cms_topic.is_customer_essential
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public Integer getIsCustomerEssential() {
        return isCustomerEssential;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.is_customer_essential
     *
     * @param isCustomerEssential the value for cms_topic.is_customer_essential
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setIsCustomerEssential(Integer isCustomerEssential) {
        this.isCustomerEssential = isCustomerEssential;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.is_sys_essential
     *
     * @return the value of cms_topic.is_sys_essential
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public Integer getIsSysEssential() {
        return isSysEssential;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.is_sys_essential
     *
     * @param isSysEssential the value for cms_topic.is_sys_essential
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setIsSysEssential(Integer isSysEssential) {
        this.isSysEssential = isSysEssential;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.is_header
     *
     * @return the value of cms_topic.is_header
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public Integer getIsHeader() {
        return isHeader;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.is_header
     *
     * @param isHeader the value for cms_topic.is_header
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setIsHeader(Integer isHeader) {
        this.isHeader = isHeader;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.sort_id
     *
     * @return the value of cms_topic.sort_id
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public Integer getSortId() {
        return sortId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.sort_id
     *
     * @param sortId the value for cms_topic.sort_id
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column cms_topic.is_valid
     *
     * @return the value of cms_topic.is_valid
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column cms_topic.is_valid
     *
     * @param isValid the value for cms_topic.is_valid
     *
     * @abatorgenerated Fri Nov 28 13:22:32 CST 2014
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }
    
    public Integer getSendSiteId() {
        return sendSiteId;
    }

   
    public void setSendSiteId(Integer sendSiteId) {
        this.sendSiteId = sendSiteId;
    }
    
    public Long getSortListAuthority() {
		return sortListAuthority;
	}

	public void setSortListAuthority(Long sortListAuthority) {
		this.sortListAuthority = sortListAuthority;
	}
	
	public Long getSortAuthoritySecondary() {
		return sortAuthoritySecondary;
	}

	public void setSortAuthoritySecondary(Long sortAuthoritySecondary) {
		this.sortAuthoritySecondary = sortAuthoritySecondary;
	}

	public Integer getIsDraft() {
		return isDraft;
	}

	public void setIsDraft(Integer isDraft) {
		this.isDraft = isDraft;
	}
    
	
}